export const TOUR_STEPS = [
  {
    id: 'welcome',
    title: '👋 Welcome to MedPOS!',
    text: 'This quick tour takes 2 minutes and shows you everything you need to start managing your pharmacy. You can skip anytime.',
    attachTo: { element: '.dashboard-header', on: 'bottom' as const },
    showOn: () => true,
    buttons: ['skip', 'next'],
    stepNumber: '1 of 8',
  },
  {
    id: 'sidebar',
    title: '📋 Your Navigation Menu',
    text: 'This sidebar has everything. POS Billing to make sales, Inventory to manage medicines, Reports for your analytics, and Settings for your store.',
    attachTo: { element: '.dashboard-sidebar', on: 'right' as const },
    buttons: ['back', 'next'],
    stepNumber: '2 of 8',
  },
  {
    id: 'dashboard-stats',
    title: '📊 Your Daily Overview',
    text: "These 4 cards show today's sales, total medicines, low stock alerts, and expiring medicines — your store's health at a glance.",
    attachTo: { element: '.dashboard-stats-row', on: 'bottom' as const },
    buttons: ['back', 'next'],
    stepNumber: '3 of 8',
  },
  {
    id: 'pos-button',
    title: '🧾 POS Billing — Most Used Feature',
    text: 'Click here to start billing customers. Search medicines, add to cart, and checkout in under 30 seconds. Supports USB barcode scanners.',
    attachTo: { element: '[href="/dashboard/pos"]', on: 'right' as const },
    buttons: ['back', 'next'],
    stepNumber: '4 of 8',
  },
  {
    id: 'inventory',
    title: '💊 Medicine Inventory',
    text: 'Search from 25,000+ Pakistan medicines and add them to your store. Set your own prices — completely independent from other stores.',
    attachTo: { element: '[href="/dashboard/inventory"]', on: 'right' as const },
    buttons: ['back', 'next'],
    stepNumber: '5 of 8',
  },
  {
    id: 'reports',
    title: '📈 Sales Reports & Analytics',
    text: 'See daily, weekly, and monthly sales. Profit & loss reports. Expiry tracking. GST tax report for FBR. All exportable to PDF and CSV.',
    attachTo: { element: '[href="/dashboard/reports"]', on: 'right' as const },
    buttons: ['back', 'next'],
    stepNumber: '6 of 8',
  },
  {
    id: 'notifications',
    title: '🔔 Smart Alerts',
    text: 'This bell shows expiry alerts, low stock warnings, and system notifications. MedPOS automatically emails you every Monday with a stock digest.',
    attachTo: { element: '.notification-bell', on: 'bottom' as const },
    buttons: ['back', 'next'],
    stepNumber: '7 of 8',
  },
  {
    id: 'help',
    title: '💬 Always Here to Help',
    text: 'Click the chat button anytime to reach our support team. We speak Urdu and English. Average response time: 15 minutes during business hours.',
    attachTo: { element: '#crisp-chatbox', on: 'top' as const },
    showOn: () => typeof window !== 'undefined' && !!(window as any).$crisp,
    buttons: ['back', 'finish'],
    stepNumber: '8 of 8',
  },
]
