import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from '@react-email/components';
import * as React from 'react';

interface MedicineReorder {
  name: string;
  currentStock: number;
  reorderLevel: number;
  suggestedOrderQty: number;
  unit: string;
}

interface SupplierReorderEmailProps {
  supplierName: string;
  supplierEmail: string;
  storeName: string;
  medicines: MedicineReorder[];
}

export const SupplierReorderEmail = ({
  supplierName,
  storeName,
  medicines,
}: SupplierReorderEmailProps) => {
  return (
    <Html>
      <Head />
      <Preview>Reorder Request from {storeName}</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section style={header}>
            <Text style={headerText}>{storeName}</Text>
            <Heading style={heading}>Reorder Request</Heading>
          </Section>

          <Section style={content}>
            <Text style={paragraph}>Dear {supplierName},</Text>
            <Text style={paragraph}>
              We would like to place an order for the following medicines to replenish our stock:
            </Text>

            <table style={table}>
              <thead>
                <tr>
                  <th style={th}>Medicine</th>
                  <th style={th}>Current Stock</th>
                  <th style={th}>Order Qty</th>
                  <th style={th}>Unit</th>
                </tr>
              </thead>
              <tbody>
                {medicines.map((m, i) => (
                  <tr key={i}>
                    <td style={td}>{m.name}</td>
                    <td style={td}>{m.currentStock}</td>
                    <td style={tdStrong}>{m.suggestedOrderQty}</td>
                    <td style={td}>{m.unit}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            <Text style={paragraph}>
              Please confirm availability and current pricing for these items.
            </Text>
            <Text style={paragraph}>
              Best regards,
              <br />
              {storeName}
            </Text>
          </Section>

          <Section style={footer}>
            <Text style={footerText}>
              This is an automated reorder request generated by MedPOS.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

export default SupplierReorderEmail;

const main = {
  backgroundColor: '#ffffff',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif',
};

const container = {
  margin: '0 auto',
  padding: '20px 0 48px',
  width: '580px',
};

const header = {
  padding: '32px 0',
  borderBottom: '1px solid #eaeaea',
};

const headerText = {
  fontSize: '14px',
  color: '#666',
  textTransform: 'uppercase' as const,
  margin: '0 0 8px',
};

const heading = {
  fontSize: '24px',
  fontWeight: 'bold',
  color: '#1a1a1a',
  margin: '0',
};

const content = {
  padding: '32px 0',
};

const paragraph = {
  fontSize: '16px',
  lineHeight: '26px',
  color: '#484848',
  margin: '16px 0',
};

const table = {
  width: '100%',
  borderCollapse: 'collapse' as const,
  margin: '24px 0',
};

const th = {
  textAlign: 'left' as const,
  fontSize: '12px',
  color: '#999',
  textTransform: 'uppercase' as const,
  paddingBottom: '8px',
  borderBottom: '1px solid #eaeaea',
};

const td = {
  padding: '12px 0',
  fontSize: '14px',
  color: '#484848',
  borderBottom: '1px solid #f1f1f1',
};

const tdStrong = {
  ...td,
  fontWeight: 'bold',
  color: '#1a1a1a',
};

const footer = {
  padding: '32px 0',
  borderTop: '1px solid #eaeaea',
};

const footerText = {
  fontSize: '12px',
  color: '#999',
  textAlign: 'center' as const,
};
